[package]
name = "mmd-anim-package-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
libfuzzer-sys = "0.4.9"
mmd-anim-package = { path = "../crates/mmd-anim-package", features = ["fuzzing"] }
zstd = "0.13.3"

[[bin]]
name = "mmdpack-header"
path = "fuzz_targets/header.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mmdpack-manifest"
path = "fuzz_targets/manifest.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mmdpack-layout"
path = "fuzz_targets/layout.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mmdpack-zstd"
path = "fuzz_targets/zstd.rs"
test = false
doc = false
bench = false
