[package]
name = "package-backends-wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm.workspace = true
package-backends-core = { path = "../core" }
ruzstd.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
zstd.workspace = true
